apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::459925047658:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build     \n- groups:\n  - system:bootstrappers\n  - system:nodes\n
    \ rolearn: arn:aws:iam::459925047658:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TCVF5AYPQQ4S\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:masters\n  rolearn: arn:aws:iam::459925047658:role/UdacityFlaskDeployCBKubectlRole\n  username: build     \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::459925047658:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TCVF5AYPQQ4S\n  username: system:node:{{EC2PrivateDNSName}}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2021-09-06T12:04:01Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"1294","uid":"902c272f-43e9-457f-9851-52c33ac95a57"}}
  creationTimestamp: "2021-09-06T12:04:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "12521"
  uid: 902c272f-43e9-457f-9851-52c33ac95a57
