# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::459925047658:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TCVF5AYPQQ4S
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::459925047658:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17C402QC9VF6L
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-06T12:04:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1294"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 902c272f-43e9-457f-9851-52c33ac95a57