apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::459925047658:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TCVF5AYPQQ4S
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
    - system:masters
      rolearn: arn:aws:iam::459925047658:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: '2021-09-06T12:04:01Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1294'
  uid: 902c272f-43e9-457f-9851-52c33ac95a57
